  
# 核心任务

- name: JupyterLab
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_nginx, tags: "role_nginx"}
    - {role: jupyterlab, tags: "jupyterlab"}
    - {role: role_preend, tags: "preend"}
    - {role: role_end, tags: "role_end"}
