# install JupyterLab
- name: install jupyterlab
  shell: |
    pip install --upgrade pip 
    pip install jupyterlab 
    pip install notebook
    jupyter notebook
    pip install voila


- name: Copy jupyterlab.service
  copy:
    src: jupyterlab.service
    dest: /lib/systemd/system/rethinkdb.service


# Enable service
- name: enable and restart jupyterlab
  service:
    name: jupyterlab.service
    state: restarted
    enabled: yes

# set soft link, -b cover the exist links
# ln -sb src des
- name: set soft link
  shell: |
    ln -sb /usr/local/etc/jupyter/  /data/config/jupyterlab
    ln -sb /usr/local/share/jupyter /data/jupyterlab
    

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check JupyterLab Version
    shell: sudo sh -c "echo `jupyter --version  |sed -n 1p` > /data/logs/install_version.txt"
    


# check service state
- name: Check JupyterLab Service
  shell: systemctl status jupyterlab | grep Active*
  register: check_jupyterlab_service
  notify: check_jupyterlab_service




